#
#   TOPPERS/ASP/FMP Kernel
#       Toyohashi Open Platform for Embedded Real-Time Systems/
#       Advanced Standard Profile Kernel
#
#   Copyright (C) 2000-2003 by Embedded and Real-Time Systems Laboratory
#                               Toyohashi Univ. of Technology, JAPAN
#   Copyright (C) 2003-2008 by Ryosuke Takeuchi
#                Platform Development Center RICOH COMPANY,LTD. JAPAN
#   Copyright (C) 2015-2019 by TOPPERS PROJECT Educational Working Group.
#
#   上記著作権者は，以下の (1)〜(4) の条件か，Free Software Foundation 
#   によって公表されている GNU General Public License の Version 2 に記
#   述されている条件を満たす場合に限り，本ソフトウェア（本ソフトウェア
#   を改変したものを含む．以下同じ）を使用・複製・改変・再配布（以下，
#   利用と呼ぶ）することを無償で許諾する．
#   (1) 本ソフトウェアをソースコードの形で利用する場合には，上記の著作
#       権表示，この利用条件および下記の無保証規定が，そのままの形でソー
#       スコード中に含まれていること．
#   (2) 本ソフトウェアを，ライブラリ形式など，他のソフトウェア開発に使
#       用できる形で再配布する場合には，再配布に伴うドキュメント（利用
#       者マニュアルなど）に，上記の著作権表示，この利用条件および下記
#       の無保証規定を掲載すること．
#   (3) 本ソフトウェアを，機器に組み込むなど，他のソフトウェア開発に使
#       用できない形で再配布する場合には，次のいずれかの条件を満たすこ
#       と．
#     (a) 再配布に伴うドキュメント（利用者マニュアルなど）に，上記の著
#         作権表示，この利用条件および下記の無保証規定を掲載すること．
#     (b) 再配布の形態を，別に定める方法によって，TOPPERSプロジェクトに
#         報告すること．
#   (4) 本ソフトウェアの利用により直接的または間接的に生じるいかなる損
#       害からも，上記著作権者およびTOPPERSプロジェクトを免責すること．
#
#   本ソフトウェアは，無保証で提供されているものである．上記著作権者お
#   よびTOPPERSプロジェクトは，本ソフトウェアに関して，その適用可能性も
#   含めて，いかなる保証も行わない．また，本ソフトウェアの利用により直
#   接的または間接的に生じたいかなる損害に関しても，その責任を負わない．
#
#  @(#) $Id: Makefile.config,v 1.2 2019/07/04 18:12:10 roi Exp $
#
 
#
#  Makefile のプロセッサ依存 (lwip用)
#

TECSPATH = $(TECSDIR)/tecs

#
#  コンパイルオプション
#
INCLUDES := $(INCLUDES) -I$(SRCDIR)/lwip -I$(SRCDIR)/lwip/lwip-2.1.2/src/include \
		-I$(SRCDIR)/lwip/lwip-2.1.2/src/include/compat/posix \
		-I$(SRCDIR)/lwip/lwip-2.1.2/src/include/lwip \
		-I$(SRCDIR)/lwip/contrib-2.1.0/ports/toppers/include -I$(SRCDIR)/lwip/contrib-2.1.0 \
		-I$(TECSPATH) \
		-I$(TECSPATH)/rpc 
SYSSVC_CFLAGS := $(SYSSVC_CFLAGS) -DETHARP_SUPPORT_STATIC_ENTRIES=1

#
#  LWIPミドルウェアに関する定義
#
SYSSVC_DIRS := $(SYSSVC_DIRS):$(SRCDIR)/lwip:\
		$(SRCDIR)/lwip/lwip-2.1.2/src/core:$(SRCDIR)/lwip/lwip-2.1.2/src/core/ipv4:$(SRCDIR)/lwip/lwip-2.1.2/src/core/ipv6:\
		$(SRCDIR)/lwip/lwip-2.1.2/src/netif:$(SRCDIR)/lwip/lwip-2.1.2/src/netif/ppp:$(SRCDIR)/lwip/lwip-2.1.2/src/netif/ppp/polarssl:\
		$(SRCDIR)/lwip/lwip-2.1.2/src/api:$(SRCDIR)/lwip/lwip-2.1.2/src/apps/snmp:$(SRCDIR)/lwip/lwip-2.1.2/src/apps/mdns:\
		$(SRCDIR)/lwip/lwip-2.1.2/src/apps/tftp:$(SRCDIR)/lwip/lwip-2.1.2/src/apps/sntp:$(SRCDIR)/lwip/lwip-2.1.2/src/apps/netbiosns:\
		$(SRCDIR)/lwip/lwip-2.1.2/src/apps/http:\
		$(SRCDIR)/lwip/contrib-2.1.0/examples/snmp/snmp_private_mib:$(SRCDIR)/lwip/contrib-2.1.0/apps/ping:\
		$(SRCDIR)/lwip/contrib-2.1.0/apps/chargen:$(SRCDIR)/lwip/contrib-2.1.0/apps/udpecho:\
		$(SRCDIR)/lwip/contrib-2.1.0/apps/tcpecho:$(SRCDIR)/lwip/contrib-2.1.0/apps/netio:\
		$(SRCDIR)/lwip/contrib-2.1.0/apps/shell:$(SRCDIR)/lwip/contrib-2.1.0/ports/toppers:\
		$(SRCDIR)/lwip/contrib-2.1.0/apps/socket_examples:\
		$(TECSPATH)/rpc 

SYSSVC_COBJS := $(SYSSVC_COBJS) init.o netif.o ip.o tcp.o tcp_in.o tcp_out.o udp.o dns.o raw.o inet_chksum.o \
	def.o stats.o pbuf.o mem.o memp.o timeouts.o etharp.o ip4.o ip4_addr.o ip4_frag.o icmp.o igmp.o dhcp.o autoip.o \
	ethip6.o ip6.o ip6_addr.o ip6_frag.o icmp6.o mld6.o nd6.o inet6.o ethernet.o slipif.o \
	tcpip.o sockets.o err.o netbuf.o api_lib.o api_msg.o if_api.o netifapi.o \
	snmp_core.o snmp_mib2.o snmp_mib2_ip.o snmp_mib2_system.o snmp_mib2_interfaces.o snmp_mib2_icmp.o snmp_mib2_tcp.o snmp_mib2_udp.o snmp_mib2_snmp.o \
	snmp_traps.o snmp_threadsync.o snmp_scalar.o snmp_table.o snmp_asn1.o snmp_pbuf_stream.o snmp_netconn.o snmp_msg.o \
	mdns.o tftp_server.o sntp.o netbiosns.o httpd.o fs.o \
	sys_arch.o snprintf.o socket_examples.o ping.o

ifdef WIFIIF
SYSSVC_COBJS := $(SYSSVC_COBJS) wifiif.o lwip_test_wifi.o
else
SYSSVC_COBJS := $(SYSSVC_COBJS) ethernetif.o lwip_test.o
endif

# PPP
#	ppp.o pppoe.o pppos.o pppol2tp.o ccp.o lcp.o fsm.o utils.o auth.o magic.o upap.o chap_ms.o chap-md5.o chap-new.o mppe.o pppcrypt.o ipcp.o ipv6cp.o vj.o
#	arc4.o md4.o md5.o sha1.o des.o
#	


