#
#  Makefile のプロセッサ依存 (motor用)
#

#
#  コンパイルオプション
#
INCLUDES	:= $(INCLUDES) -I$(SRCDIR)/tmc -I$(SRCDIR)/tmc/TMC-API

#
#  モーターに関する定義
#
#SYSSVC_DIRS := $(SYSSVC_DIRS):$(SRCDIR)/tmc
#SYSSVC_COBJS := $(SYSSVC_COBJS) 
